# Generated by Django 4.2.7 on 2026-02-10 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('payment', '0001_initial'), ('payment', '0002_alter_payment_card_number')]

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('card', 'Онлайн картой'), ('random_account', 'Онлайн со случайного чужого счёта')], max_length=20, verbose_name='Способ оплаты')),
                ('card_number', models.CharField(max_length=16, verbose_name='Номер карты/счета')),
                ('card_name', models.CharField(max_length=255, verbose_name='Имя на карте')),
                ('card_month', models.CharField(max_length=2, verbose_name='Месяц окончания')),
                ('card_year', models.CharField(max_length=4, verbose_name='Год окончания')),
                ('card_code', models.CharField(max_length=4, verbose_name='CVV/CVC код')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'В обработке'), ('completed', 'Оплачено'), ('failed', 'Ошибка оплаты'), ('refunded', 'Возвращено')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID транзакции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-created_at'],
            },
        ),
    ]
