# Generated by Django 6.0 on 2025-12-15 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='static/categories/placeholder.jpg', null=True, upload_to='static/categories/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='static/products/placeholder.jpg', upload_to='static/products/'),
        ),
    ]
